inherit_gem:
  decidim-dev: rubocop-decidim.yml

AllCops:
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - "development_app/**/*"
    - "spec/decidim_dummy_app/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
